### ISSUE TITLE
Getting error java.lang.NoSuchMethodError: okhttp3.RequestBody.create(Ljava/lang/String;Lokhttp3/MediaType;)Lokhttp3/RequestBody;

### ISSUE THREAD

**Issue by sunnysachdeva99** [Visual-Regression-Tracker/Visual-Regression-Tracker#79] opened 2020-07-22 10:06 UTC
I am using Visual Tracker with Selenium Webdriver Java ( not selenide). 

I had to change the port in env since 8080 was already taken by some other process 
========================================================================
.env
========================================================================
# Frontend
REACT_APP_API_URL=http://localhost:4200
PORT=8686

# Backend
JWT_SECRET='jwtPrivateKey'
JWT_LIFE_TIME=1d

IMG_UPLOAD_FOLDER=imageUploads/
BODY_PARSER_JSON_LIMIT="1mb"

APP_PORT=4200
APP_FRONTEND_URL=http://localhost:8080

# DB
POSTGRES_PORT=5432
POSTGRES_USER=postgres
POSTGRES_PASSWORD=postgres
POSTGRES_DB=vrt_db

========================================================================
docker-compose looks like
========================================================================
version: "3.7"
services:
  ui:
    image: visualregressiontracker/ui:2.0.0
    ports:
      - "${PORT}:8080"
    environment: 
      REACT_APP_API_URL: ${REACT_APP_API_URL}
  api:
    image: visualregressiontracker/api:2.0.0
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:${POSTGRES_PORT}/${POSTGRES_DB}
      JWT_SECRET: ${JWT_SECRET}
      JWT_LIFE_TIME: ${JWT_LIFE_TIME}
      IMG_UPLOAD_FOLDER: ${IMG_UPLOAD_FOLDER}
      APP_FRONTEND_URL: ${APP_FRONTEND_URL}
      BODY_PARSER_JSON_LIMIT: ${BODY_PARSER_JSON_LIMIT}
    ports:
      - "${APP_PORT}:3000"
    expose:
      - "${APP_PORT}"
    volumes:
      - ./imageUploads:/${IMG_UPLOAD_FOLDER}
    depends_on:
      - postgres
  postgres:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    expose:
      - "${POSTGRES_PORT}"
    volumes:
      - postgres:/var/lib/postgresql/data
  migration:
    image: visualregressiontracker/migration:2.0.0
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:${POSTGRES_PORT}/${POSTGRES_DB}
    depends_on:
      - postgres
volumes:
  postgres:

========================================================================
CODE
========================================================================

public class VisualTest {

    protected WebDriver driver;
    VisualRegressionTracker visualRegressionTracker;
    @BeforeSuite
    public void bs() throws InterruptedException {

        VisualRegressionTrackerConfig config = new VisualRegressionTrackerConfig(
                "http://localhost:8686", // replace with your data
                "Goole", // replace with your data
                "41d0bcef-f26e-46a8-8d6a-95c0d39dc70a", // replace with your data
                "Main" // replace with your data
        );

        visualRegressionTracker = new VisualRegressionTracker(config);

        WebDriverManager.chromedriver().setup();
        driver= new ChromeDriver();
        driver.get("https://google.com");
        Thread.sleep(3000);
        driver.manage().window().setSize(new Dimension(1200,800));
    }
    @Test
    public void testExample() throws IOException {
        visualRegressionTracker.track(
                "Home page",
                ((TakesScreenshot) driver).getScreenshotAs(OutputType.BASE64),
                TestRunOptions.builder()
                        .diffTollerancePercent(0)
                        .build()
        );
    }

    @AfterSuite
    public void tearDown() {
        driver.close();
    }
}

========================================================================
ERROR
========================================================================
java.lang.NoSuchMethodError: okhttp3.RequestBody.create(Ljava/lang/String;Lokhttp3/MediaType;)Lokhttp3/RequestBody;

	at io.visual_regression_tracker.sdk_java.VisualRegressionTracker.startBuild(VisualRegressionTracker.java:34)
	at io.visual_regression_tracker.sdk_java.VisualRegressionTracker.track(VisualRegressionTracker.java:78)
	at com.visualtracker.VisualTest.testExample(VisualTest.java:46)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.testng.TestRunner.privateRun(TestRunner.java:766)
	at org.testng.TestRunner.run(TestRunner.java:587)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
	at org.testng.SuiteRunner.run(SuiteRunner.java:286)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
	at org.testng.TestNG.runSuites(TestNG.java:1039)
	at org.testng.TestNG.run(TestNG.java:1007)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:110)

**Comment by pashidlos** [comment] 2020-07-22 10:36
hi @sunnysachdeva99!
thanks for detailed report! 

here I could see two issues:
1. as you changed frontend PORT in `.env` you need to change port as well in backend section that refers to frontend url `APP_FRONTEND_URL=http://localhost:8686` but that is not the cause of this error
2. the exception that you are getting is because some library versions are conflicting, check your dependency tree if there are several versions of `okhttp3` and keep only one, or add direct dependency to needed version `com.squareup.okhttp3:okhttp:4.8.0`

please, let me know if it worked for you

**Comment by sunnysachdeva99** [comment] 2020-07-22 11:52
Thanks, @pashidlos for your quick reply.

Found that selenium-java also uses okhttp3 , hence I excluded it and have this in visual-tracker

But now I got below error. I am using webdrivermanager to launch browser. This dependency also uses google gson and I see from your check-in comment that you have removed webdrivermanager "webdrivermanager dependency removed". Is there a problem if I use webdrivermanager ?


com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $

	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:226)
	at com.google.gson.Gson.fromJson(Gson.java:932)
	at com.google.gson.Gson.fromJson(Gson.java:897)
	at com.google.gson.Gson.fromJson(Gson.java:846)
	at com.google.gson.Gson.fromJson(Gson.java:817)
	at io.visual_regression_tracker.sdk_java.VisualRegressionTracker.startBuild(VisualRegressionTracker.java:43)
	at io.visual_regression_tracker.sdk_java.VisualRegressionTracker.track(VisualRegressionTracker.java:78)

**Comment by pashidlos** [comment] 2020-07-22 12:07
No, no problem, the reason to remove `webdrivermanager` was that it's already included in `selenide` as peer dependency so no need to duplicate it

next error is also seems strange to me, could you check if there any error in docker logs?
also try with example project?

**Comment by sunnysachdeva99** [comment] 2020-07-23 04:43
I am getting the same error using the example project. Please see the screenshot

<img width="1405" alt="Screenshot 2020-07-23 at 10 13 09" src="https://user-images.githubusercontent.com/60193936/88252797-23404d00-cccd-11ea-8e03-d7c6f4b593dc.png">

**Comment by pashidlos** [comment] 2020-07-23 07:20
ok, then seems the problem in the backend api
is the frontend working fine? so you are able to login and create new projects?
try going to the url where backend is working `http://localhost:4200/api` it's a swagger page with all endpoints
find `POST /build`, auth with apiKey and try sending request with your project name and branch
let me know if you are getting the error response

**Comment by sunnysachdeva99** [comment] 2020-07-23 07:31
My updated .env looks like

# Frontend
REACT_APP_API_URL=http://localhost:4200
PORT=8686

# Backend
JWT_SECRET='jwtPrivateKey'
JWT_LIFE_TIME=1d

IMG_UPLOAD_FOLDER=imageUploads/
BODY_PARSER_JSON_LIMIT="1mb"

APP_PORT=4200
APP_FRONTEND_URL=http://localhost:8686


# DB
POSTGRES_PORT=5432
POSTGRES_USER=postgres
POSTGRES_PASSWORD=postgres
POSTGRES_DB=vrt_db


I am able to create projects from front end which is pointing to http://localhost:8686/projects
However, if I open http://localhost:8686/api then I get error " Validation failed (UUID is expected)


<img width="1421" alt="Screenshot 2020-07-23 at 12 53 37" src="https://user-images.githubusercontent.com/60193936/88261456-f3507400-cce3-11ea-81e8-100820ca502b.png">

**Comment by pashidlos** [comment] 2020-07-23 07:36
use backend port `4200` by default instead of `8686`

**Comment by pashidlos** [comment] 2020-07-23 07:40
this should work for you `http://localhost:4200/api`

**Comment by sunnysachdeva99** [comment] 2020-07-23 08:01
curl -X POST "http://localhost:4200/builds" -H "accept: */*" -H "apiKey: 41d0bcef-f26e-46a8-8d6a-95c0d39dc70a" -H "Content-Type: application/json" -d "{\"branchName\":\"Main\",\"project\":\"GoogleTest\"}"


Response body
Download
{
  "statusCode": 403,
  "message": "Forbidden resource",
  "error": "Forbidden"
}
Response headers
 access-control-allow-origin: * 
 connection: keep-alive 
 content-length: 69 
 content-type: application/json; charset=utf-8 
 date: Thu, 23 Jul 2020 08:00:28 GMT 
 etag: W/"45-T7Txzr/IRLfQ4TEPfbVWLpgje4Q" 
 x-powered-by: Express

**Comment by pashidlos** [comment] 2020-07-23 08:21
set up is fine
the problem is in `apiKey` it's used to identify specific user
go to User Profile page and you will find one, use it instead of project ID

we gonna fix the text on project page in this task https://github.com/Visual-Regression-Tracker/Visual-Regression-Tracker/issues/52

**Comment by sunnysachdeva99** [comment] 2020-07-23 09:08
in Swagger, it worked after changing to Project ID. However, in the code, still the same error.

@pashidlos this project looks very cool. In terms, of testing, let me know if I can contribute

**Comment by pashidlos** [comment] 2020-07-23 09:20
could you double check if `apiKey` was updated in code of your tests? 
on the screen you shared before I see that there is project ID is used

in terms of contribution you are more than welcome here!
before official release I announce pre-release state when you could also participate
I announce them in telegram https://t.me/visual_tracker or in twitter https://twitter.com/VisualReTracker
just in case you want some practice in development, there are some issues marked as `good first issue`

**Comment by sunnysachdeva99** [comment] 2020-07-23 10:22
yes i double checked. with both api, same error

**Comment by pashidlos** [comment] 2020-07-23 10:44
could you upload your code somewhere on github? 
together with `.env` and `docker-compose.yml`

**Comment by sunnysachdeva99** [comment] 2020-07-24 04:31
https://github.com/sunnysachdeva99/Visual_Regression/blob/master/src/test/java/com/practice/AppTest.java

**Comment by pashidlos** [comment] 2020-07-24 07:22
this is what I've changed to make it working, main problem was in `apiUrl`, it should be link to backend api, change to `4200`

let me know your result
![1](https://user-images.githubusercontent.com/5182956/88368850-21d75900-cd8f-11ea-967c-72dfc2c7d2e5.png)

**Comment by sunnysachdeva99** [comment] 2020-07-24 10:18
you are right , when I changed to backend port, then I am not getting error. However, one question on baseline images.

The way Applitoos or other providers work is when we run the automation for the first time, it uploads the screenshot and considers it as a baseline. 

Help me understand how does it work for  Visual-Regression-Tracker ? During its installation, docs mentioned to create imageUploads folder. 
Do we need to take screenshot manually and add it in imageUploads folder ?

**Comment by pashidlos** [comment] 2020-07-24 10:34
- regarding baseline, right now it's not supported to accept first image as baseline 
the thing is that for me make sense to force user visually review image before accepting it as baseline, otherwise it's possible that you keep asserting baseline that might not be as expected (as it was auto accepted)
feel free to submit feature request for that, I'll consider it

- image folder
no, it's only to persist the data from container that after they are recreated you don't loos images, add image only via tests

thanks for making project better!

**Closed by pashidlos** 2020-07-24 10:34 UTC
Labels: bug, waiting
