### ISSUE TITLE
 POST /test-run, 500 Error: Internal Server Error ReferenceError: it is not defined

### ISSUE THREAD

**Issue by alexstepanyuk** [Visual-Regression-Tracker/Visual-Regression-Tracker#361] opened 2022-05-26 09:34 UTC
After installing the docker container, I tried to call POST /test-run through the swagger, got the following error in response: 500 Error: Internal Server Error ReferenceError: it is not defined.

Request body:
```
{
  "name": "Image name",
  "os": "Mac",
  "browser": "Chrome",
  "viewport": "800x600",
  "device": "PC",
  "branchName": "master",
  "diffTollerancePercent": 1,
  "ignoreAreas": [
    {
      "x": 10,
      "y": 20,
      "width": 300,
      "height": 400
    }
  ],
  "imageBase64": "123"
}
```

Responses:
500 Error: Internal Server Error
```
{
  "path": "/test-runs",
  "name": "ReferenceError",
  "message": "it is not defined",
  "exception": {},
  "stack": "
	ReferenceError: it is not defined
	at Object.transformFn (/dist/test-runs/dto/create-test-request.dto.js:59:13)
	at /node_modules/class-transformer/cjs/TransformOperationExecutor.js:358:30
	at Array.forEach (<anonymous>)
	at TransformOperationExecutor.applyCustomTransformations (/node_modules/class-transformer/cjs/TransformOperationExecutor.js:357:19)
	at TransformOperationExecutor.transform (/node_modules/class-transformer/cjs/TransformOperationExecutor.js:300:47)
	at ClassTransformer.plainToInstance (/node_modules/class-transformer/cjs/ClassTransformer.js:27:25)
	at Object.plainToClass (/node_modules/class-transformer/cjs/index.js:34:29)
	at ValidationPipe.transform (/node_modules/@nestjs/common/pipes/validation.pipe.js:51:39)
	at /node_modules/@nestjs/core/pipes/pipes-consumer.js:16:33
	at processTicksAndRejections (internal/process/task_queues.js:97:5)"
}
```

**Comment by pashidlos** [comment] 2022-05-26 12:29
@alexstepanyuk thank for reporting 

could you check with proper `imageBase64` value?
need to know whether it's general issue or just validation message to fix

**Comment by alexstepanyuk** [comment] 2022-05-27 03:27
ImageBase64 value was checked, error occurs for any value. Also dotnet code with real screen also returned this error. 
We also tested POST /test-runs/multipart. With valid values, it throws the following error:
```
{
  "path": "/test-runs/multipart",
  "name": "SyntaxError",
  "message": "Unexpected end of JSON input",
  "exception": {},
  "stack": "SyntaxError: Unexpected end of JSON input
        at JSON.parse (<anonymous>)
        at Object.transformFn (/dist/test-runs/dto/create-test-request.dto.js:61:21)
        at /node_modules/class-transformer/cjs/TransformOperationExecutor.js:358:30
        at Array.forEach (<anonymous>)
        at TransformOperationExecutor.applyCustomTransformations (/node_modules/class-transformer/cjs/TransformOperationExecutor.js:357:19)
        at TransformOperationExecutor.transform (/node_modules/class-transformer/cjs/TransformOperationExecutor.js:300:47)
        at ClassTransformer.plainToInstance (/node_modules/class-transformer/cjs/ClassTransformer.js:27:25)
        at Object.plainToClass (/node_modules/class-transformer/cjs/index.js:34:29)
        at ValidationPipe.transform (/node_modules/@nestjs/common/pipes/validation.pipe.js:51:39)
        at /node_modules/@nestjs/core/pipes/pipes-consumer.js:16:33"
}
```

**Comment by arvindgh** [comment] 2022-05-27 05:54
I am also facing the same issue with dotnet sdk -
**Responses: 500 Error: Internal Server Error**, 
Working fine when called the same api(with same values) with postman.
\
Do you know what could be the issue with dotnet sdk?

**Comment by pashidlos** [comment] 2022-05-27 13:27
could you reproduce the same issue with dotnet sdk with example from here?
https://github.com/Visual-Regression-Tracker/examples-dotnet

**Comment by alexstepanyuk** [comment] 2022-06-01 06:31
> could you reproduce the same issue with dotnet sdk with example from here? https://github.com/Visual-Regression-Tracker/examples-dotnet

yes

**Comment by arvindgh** [comment] 2022-06-01 06:37
The Issue is with the **merge** field inside CreateTestRequestDto, even if we pass the value it is failing, without pass it is taking default value.

After removing the merge field it is working as expected.

**Comment by alexstepanyuk** [comment] 2022-06-28 06:36
@arvindgh, please, can you tell me, how to make it work properly at the moment? Where to remove the merge field?

**Comment by arvindgh** [comment] 2022-07-14 07:02
@alexstepanyuk Remove the field from APIClient.cs in the obj folder
Also move this file to your project folder and remove the swagger dependency, so that it wont create this file on each build.

**Comment by wasder** [comment] 2022-08-05 17:20
Got this error when I try to add ignoreAreas object. Without this object it works.

With ignoreAreas request:
https://gist.github.com/wasder/e6107122ac8e7f4b643e9dcef8197a8e

Response:
```
[Nest] 22  - 08/05/2022, 5:02:32 PM     LOG [TestRunsService] Try AutoApproveByNewBaselines testRun: e95486f9-09ba-4def-bb3c-8e6192ec536b
[Nest] 22  - 08/05/2022, 5:10:25 PM   ERROR [ReferenceError: it is not defined
    at Object.transformFn (/dist/test-runs/dto/create-test-request.dto.js:59:13)
    at /node_modules/class-transformer/cjs/TransformOperationExecutor.js:358:30
    at Array.forEach (<anonymous>)
    at TransformOperationExecutor.applyCustomTransformations (/node_modules/class-transformer/cjs/TransformOperationExecutor.js:357:19)
    at TransformOperationExecutor.transform (/node_modules/class-transformer/cjs/TransformOperationExecutor.js:300:47)
    at ClassTransformer.plainToInstance (/node_modules/class-transformer/cjs/ClassTransformer.js:27:25)
    at Object.plainToClass (/node_modules/class-transformer/cjs/index.js:34:29)
    at ValidationPipe.transform (/node_modules/@nestjs/common/pipes/validation.pipe.js:51:39)
    at /node_modules/@nestjs/core/pipes/pipes-consumer.js:16:33
    at processTicksAndRejections (internal/process/task_queues.js:97:5)] ReferenceError: it is not defined
 ```

Without:
https://gist.github.com/wasder/cc8e8dcff896164c1800cab766b2846a

API ver 4.20.2

**Comment by polyvisual** [comment] 2022-09-02 06:56
So does this need fixing in the dotnet sdk, or in the api package?

**Comment by nGervasyuk** [comment] 2022-09-16 09:05
Reproduced the same issue with our wrapper for swift, so looks like need to fix on the backend

**Comment by pashidlos** [comment] 2022-09-19 08:31
@polyvisual @nGervasyuk right, it should be fixed on backend 
this line refers no not defined variable `it`
https://github.com/Visual-Regression-Tracker/backend/blob/0a3edf80c4170e3aecaa74dc9ff32674ef2c4f91/src/test-runs/dto/create-test-request.dto.ts#L42

**Comment by nGervasyuk** [comment] 2022-11-10 05:57
@pashidlos 
any information on this issue?

**Comment by mseremin** [comment] 2023-03-10 10:23
@pashidlos is there any chance this will be fixed?

**Comment by polyvisual** [comment] 2023-03-15 18:01
@pashidlos I have created a PR at https://github.com/Visual-Regression-Tracker/backend/pull/199

It took a bit of work to get the postgres docker, vrt backend and vrt frontend running, but I managed to successfully create a test in vrt.

**Comment by pashidlos** [comment] 2023-03-16 13:04
@polyvisual thanks for contribution! 
gonna make a release for it af ter merged

**Closed** 2023-03-17 09:58 UTC
Labels: bug, api
